server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: bank-rest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/bank-rest}
    username: ${SPRING_DATASOURCE_USERNAME:mira}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_RESOURCE_SERVER_ISSUER_URI:http://localhost:9090}
      authorizationserver:
        issuer: ${SPRING_SECURITY_AUTH_SERVER_ISSUER_URI:http://localhost:9090}

  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    com.example.bankcards.*: debug